### PR TITLE
Updating Offset Removal Process

### PR DESCRIPTION
**Pull request by jpilgram**
Changed Offset removal process to caluclate offset from uncut, orginial source data instead of from the data that has been cut to align t0s

### CODE REVIEW

**Comment by pheuer** [comment]
If you do it this way, doesn't that mean that the offset cannot be specified relative to t0? In that case you'd have to be very careful to specify an offset range (on the raw signal) that was smaller than the smallest t0ind. If you did that it would work ok, but that would be equivalent to cutting the data first?

Why do you want to calculate it from the unshifted data?


Here's a diagram of what I mean: you don't gain any additional length to calculate the offset by doing this.
t0ind

What might make sense would be to calculate the offset from 0 to t0ind on the raw traces prior to shifting, but in that case you'll need to calculate a custom offset range for each trace which isn't what you're doing here.

**Comment by dschaeffer17** [comment]
I agree with Peter, it's not clear to me why this should be the default behavior.  If there's a good reason to do this, it would be better as an optional flag.

**Comment by jpilgram** [comment]
Maybe I misinterpreted the way the code was working, I thought that the
code found where the t0 index was in the uncut data then decided how to
take the offset off from there. If that's not the case then I guess this
doesn't work. However, I think that by cutting the data to start at t0 then
removing the offset, we are missing the best chunk of noise to use as
offset removal which would be all the noise we get before the laser fires.

I also ran the code through with this change and it got rid of the strange
points in the data that were converging to zero near the end of the data
range. It can easily be changed back if you think that this is not the
correct thinking.

-Jessica

**Comment by pheuer** [comment]
So, the code never cuts the data at t0, it finds the shot that has the smallest t0ind then cuts a bit off every other trace so that their t0ind's are shifted to match. The result should be traces that start at the same (negative) time before t0. However you're right that this does shorten the space for computing the offset, and in the Biermann experiments I can see why that's an issue.

The problem with your current draft is that currently when 'offset_rel_t0' is set, the indices are being computed relative to t0 _in the already shifted arrays_. So, I think you'd also have to change the ways 'offset_a' and 'offset_b' are calculated in the case where one or both of the values in  'offset_rel_t0' is True.

One other potential concern is that, as currently written, you are accessing the file twice which may be slower. That might matter on large planes. Maybe it'd be better to load the whole trace in one go and then cut it up as needed?

**Comment by jpilgram** [comment]
Ok, so I think my biggest issue is that I thought I understood how the code
worked but am now realizing that it is even more complicated than I
thought. I think I should change it back to the original code.

I have no idea what else to try to see if the offset removal is causing the
conversion at the end of the data sets because I don't think that it is
physical. If you have any ideas, let me know.

Best,
Jessica

**Comment by dschaeffer17** [comment]
Jessica,

It seems telling that playing around with the offsets solved your weird signal convergence issue.  Even if the code works differently than you thought, there might still be an issue related to offsets.  I would suggest focusing on a single example where you see the weird convergence, and following the signal processing from beginning to end to see if you can identify where the problem is.  I would take the raw trace and write your own code to reproduce the different processing steps (since it's just one example, you don't need all the edge case code and options, so it should be much simpler).

**Comment by pheuer** [comment]
I agree with @dschaeffer17 : based on what you described it sounds very likely that there are too few points being included in the offset calculation, and that your fix solves this problem for your specific case.

As far as making that change in the main version of uclahedp, I support it if you can figure out the indices math to make sure that setting the offset range relative to t0 works: that's an important feature for LAPD datasets that we definitely need to continue to support.

**Pull request closed without merging**
